[package]
name = "open-vcdiff-rs-bindings"
description = "Rust bindings for Google's open-vcdiff C++ library"
version = "0.1.0"
edition = "2021"


[build-dependencies]
bindgen = "0.69.4"
cc = "1.0.92"
tempfile = "3.10.1"
