[package]
name = "open-vcdiff-rs-bindings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.69.4"
cc = "1.0.92"
tempfile = "3.10.1"
